### ISSUE TITLE
US1 display medication on main page

### ISSUE THREAD

**Issue by Miladu93** [Miladu93/meinMedikamentenTagebuch#2]
## Value Proposition

As a user I want to see a list of medications (dummy data)
so that i have a good overview'
​

## Description
![image](https://github.com/Miladu93/meinMedikamentenTagebuch/assets/134289363/cd713907-9dd5-40ff-b6ca-87e9f2d659ed)
​

## Acceptance Criteria

- a list of added medications (dummy data) should be viewed on the main page
- Each medication entry in the list should show the medication name and dosage of the dummy date

## Tasks

- create a new branch
- create dummy data
- create medication component
- render the list

**Comment by Miladu93** [comment]
US1

**Comment by actyvystom** [comment]
A good start! 👍🏻 
Anyway some comments: 
- your value proposition is basically fine  and a nice one for the first user story - but neither scribble, acceptance criteria nor tasks fit to it as you are already mentioning adding medications, input fields etc.
I suggest to stick with this value proposition and adjust scribble and acceptance criteria, e.g. 
- a list of medications is shown
- the list is scrollable if there are entries below the fold  

For tasks, remove all the input and adding entries and also mention where you plan to get your medication data from (create static sample data, API etc.)

**Comment by Miladu93** [comment]
i should have mentioned that my app has a main page and a weekly overview page. on the main page medications are entered by the user and these are selected in the weekly overview page and inserted in the weekdays from monday to sunday. so i get my data from the user directly. I have also edited my value proposition so it fits more with the scribble, cirteria und tasks

**Comment by Roland-Hufnagel** [comment]
Hi Milad. This one is quite to big. Start very simple. A good first userstory (like Thomas said) could be displaying a list of medications. Therefor you can use dummy data (an array with medication-objects or even the names of medications).So the value proposition could be: 'As a user I see a list of medications to have a good overview'. Write some simple acceptance-criterias for this scenario and add the tasks (create dummy data, create medication component, ...

Please make every userstory as simple as can be. Then step by step add more features in the next userstories. 

And please add a title to your userstory.

**Comment by Roland-Hufnagel** [comment]
Hi Milad, I think you are on the right way. But only some minor changes I request:
There are two possibilities: 
Either you delete the 'Add'-functionality from this userstory and only display the list from the dummy data (this one I prefer)
or
define the 'Add'-functionality also in the title of the userstory, in the acceptance-criteria and in the tasks

**Comment by Roland-Hufnagel** [comment]
just the value proposition has to be adapted and to render the list would be a good task.

**Comment by Roland-Hufnagel** [comment]
This looks good now 🎉 Go on in the same way with the next userstories.
